### ISSUE TITLE
Is there any way to configure what gets outputed to the console?

### ISSUE THREAD

**Issue by mdownes** [poppinlp/grunt-htmlhint-plus#17]
Currently, the following line of code outputs every file that hinted correctly. 
grunt.log.ok('HtmlHintPlus: ' + file + ' hint well...');

With a large project, this is far too much information and only failures should be reported.
Could a change be made to only do this in verbose mode? like the following:
grunt.**verbose**.ok('HtmlHintPlus: ' + file + ' hint well...');

Thanks,

Maurice

**Comment by poppinlp** [comment]
This feature has been added by @mwmckee since version 0.4.3
