### ISSUE TITLE
please update to 0.9.14+

### ISSUE THREAD

**Issue by bonesoul** [poppinlp/grunt-htmlhint-plus#18]
related to: https://github.com/yaniswang/HTMLHint/issues/194

**Comment by poppinlp** [comment]
THX. Seems like htmlhint hasn't published 0.9.14. The newest version on NPM is [0.9.13](https://www.npmjs.com/package/htmlhint).
I'll update to 0.9.14 if it's published.

**Comment by poppinlp** [comment]
Hi.
I have published version 0.5.1. Dose this issue goes on?
