### ISSUE TITLE
Support custom rules as documented on htmlhint

### ISSUE THREAD

**Issue by KurtWagner** [poppinlp/grunt-htmlhint-plus#20]
Hello,

I notice the way to implement custom rules mentioned in the htmlhint documentation [here](https://github.com/yaniswang/HTMLHint/wiki/Usage#load-custom-rules) differs from the way this tool loads the rules in `options.customRules` (i.e, [here](https://github.com/poppinlp/grunt-htmlhint-plus/blob/9d569e7a93f7b2a6e89fdeaebab2044fe7ad7863/tasks/htmlhintplus.js#L60)). It expects an `object` where as the module for htmlhint exports a function.

Would it be ok for me to update the `options.customRules` to _also_ support `typeof customRule === 'function'`?

Thanks for the package.

**Comment by poppinlp** [comment]
Sure. Great. :)

**Comment by poppinlp** [comment]
Thanks. I'll publish it today.
Actually i'm not maintained this repo since a long time ago. And i think you know what you are doing. So if you wanna do more, just go and make it.
If you would like and you think it's necessary, i'll add you to collaborators to maintain this repo. :)

**Comment by KurtWagner** [comment]
Thanks @poppinlp 😄 I'm happy to help collaborate

**Comment by poppinlp** [comment]
OK. Already invite. Thanks.
